const COLOR_MAP_NAME = {
  jet: "jet",
  hsv: "hsv",
  hot: "hot",
  spring: "spring",
  summer: "summer",
  autumn: "autumn",
  winter: "winter",
  bone: "bone",
  copper: "copper",
  greys: "greys",
  yignbu: "yignbu",
  greens: "greens",
  yiorrd: "yiorrd",
  bluered: "bluered",
  rdbu: "rdbu",
  picnic: "picnic",
  rainbow: "rainbow",
  portland: "portland",
  blackbody: "blackbody",
  earth: "earth",
  electric: "electric",
  alpha: "alpha",
  viridis: "viridis",
  inferno: "inferno",
  magma: "magma",
  plasma: "plasma",
  warm: "warm",
  cool: "cool",
  "rainbow-soft": "rainbow-soft",
  bathymetry: "bathymetry",
  cdom: "cdom",
  chlorophyll: "chlorophyll",
  density: "density",
  "freesurface-blue": "freesurface-blue",
  "freesurface-red": "freesurface-red",
  oxygen: "oxygen",
  par: "par",
  phase: "phase",
  salinity: "salinity",
  temperature: "temperature",
  turbidity: "turbidity",
  "velocity-blue": "velocity-blue",
  "velocity-green": "velocity-green",
  cubehelix: "cubehelix",
};

module.exports = {
  colormapName: COLOR_MAP_NAME,
};
